baseurl = "https://example.com"
title = "HackCU"
author = "HackCU"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"

pygmentsUseClasses=true

#disqusShortname = ""
#googleAnalytics = ""

[params]
author = "HackCU"
introDescription = "Welcome to the CU Boulder Cybersecurity Club. Here you will find all sorts of resources to support your hacking needs."
contentSharing = "I'm happy for you to share content on this site, but please provide attribution."

[social]
instagram = "tbd"
linkedin = "tbd"
twitter = "tbd"

